POST http://host.docker.internal:8080/auth/realms/discord/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest&client_secret=34712ea6-9abb-4dde-9164-0f95e2fdafa4&grant_type=password&scope=openid&username=navarro.ime@gmail.com&password=123456